{
  "openapi": "3.0.0",
  "info": {
    "title": "Event Manager",
    "description": "Event Manager is an application where users who are managed by admin can create events and choose a center where they want the event to take place",
    "version": "1.0",
    "contact": "email: kenolusola@gmail.com"
  },
  "servers": [
    {
      "url": "http://localhost:8000",
      "variables": {}
    }
  ],
  "paths": {
    "/api/v1/users": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Get All Users",
        "description": "API endpoint to get all users in the application",
        "operationId": "GetAllUsers",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwOTkxNywiZXhwIjoxNTI2NTgyNzE3fQ.vJWnidUiNieFE-tof_MiJTBWad5trZWQyrnPEY9pkbI"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwOTkxNywiZXhwIjoxNTI2NTgyNzE3fQ.vJWnidUiNieFE-tof_MiJTBWad5trZWQyrnPEY9pkbI"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Sign Up, creates new users",
        "description": "Allows users of the application to sign up",
        "operationId": "SignUp",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            },
            "example": "application/x-www-form-urlencoded"
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "required": [
                  "firstname",
                  "lastname",
                  "email",
                  "password"
                ],
                "type": "object",
                "properties": {
                  "firstname": {
                    "type": "string",
                    "example": "Bala"
                  },
                  "lastname": {
                    "type": "string",
                    "example": "Ahmed"
                  },
                  "email": {
                    "type": "string",
                    "example": "bala@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "1234567890"
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "201": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "example": {
                    "status": "Success",
                    "message": "User successfully signed up",
                    "data": {
                      "firstname": "kunle",
                      "lastname": "williams",
                      "role": "user",
                      "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjQsImlzYWRtaW4iOmZhbHNlLCJ1c2Vycm9sZSI6InVzZXIiLCJpYXQiOjE1MjY0MDgzMzMsImV4cCI6MTUyNjU4MTEzM30.ziozx4c9yxvPDeGBefawbHEzeB0dh6Kz1-2EkNyvb-4"
                    }
                  },
                  "$ref": "#/components/schemas/SignUp"
                },
                "example": {
                  "status": "Success",
                  "message": "User successfully signed up",
                  "data": {
                    "firstname": "kunle",
                    "lastname": "williams",
                    "role": "user",
                    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjQsImlzYWRtaW4iOmZhbHNlLCJ1c2Vycm9sZSI6InVzZXIiLCJpYXQiOjE1MjY0MDgzMzMsImV4cCI6MTUyNjU4MTEzM30.ziozx4c9yxvPDeGBefawbHEzeB0dh6Kz1-2EkNyvb-4"
                  }
                }
              }
            }
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/api/v1//users/login": {
      "post": {
        "tags": [
          "Users/Admin"
        ],
        "summary": "Sign In",
        "description": "API route that allows users sign in to the application",
        "operationId": "SignIn",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            },
            "example": "application/x-www-form-urlencoded"
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "required": [
                  "email",
                  "password"
                ],
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "kenolusola@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "Iimpeccable1"
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/api/v1//centers": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Get All Centers",
        "description": "API endpoint to get all centers",
        "operationId": "GetAllCenters",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwOTkxNywiZXhwIjoxNTI2NTgyNzE3fQ.vJWnidUiNieFE-tof_MiJTBWad5trZWQyrnPEY9pkbI"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwOTkxNywiZXhwIjoxNTI2NTgyNzE3fQ.vJWnidUiNieFE-tof_MiJTBWad5trZWQyrnPEY9pkbI"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Create Center",
        "description": "API route that allows Superadmin and Admin create a center",
        "operationId": "CreateCenter",
        "parameters": [
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            },
            "example": "application/x-www-form-urlencoded"
          },
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwOTkxNywiZXhwIjoxNTI2NTgyNzE3fQ.vJWnidUiNieFE-tof_MiJTBWad5trZWQyrnPEY9pkbI"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwOTkxNywiZXhwIjoxNTI2NTgyNzE3fQ.vJWnidUiNieFE-tof_MiJTBWad5trZWQyrnPEY9pkbI"
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "required": [
                  "name",
                  "location",
                  "description",
                  "capacity",
                  "facilities",
                  "image",
                  "price"
                ],
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Emerald Enclave"
                  },
                  "location": {
                    "type": "string",
                    "example": "6, Aminu street Garki Abuja"
                  },
                  "description": {
                    "type": "string",
                    "example": "For your eyes only"
                  },
                  "capacity": {
                    "type": "string",
                    "example": "200"
                  },
                  "facilities": {
                    "type": "string",
                    "example": "swimming pool"
                  },
                  "image": {
                    "type": "string",
                    "example": "\"\""
                  },
                  "price": {
                    "type": "string",
                    "example": "10000"
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/api/v1/centers/{centerId}": {
      "get": {
        "tags": [
          "Admin"
        ],
        "summary": "Get One Center",
        "description": "API endpoint to get one center",
        "operationId": "GetOneCenter",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwOTkxNywiZXhwIjoxNTI2NTgyNzE3fQ.vJWnidUiNieFE-tof_MiJTBWad5trZWQyrnPEY9pkbI"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwOTkxNywiZXhwIjoxNTI2NTgyNzE3fQ.vJWnidUiNieFE-tof_MiJTBWad5trZWQyrnPEY9pkbI"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "put": {
        "tags": [
          "Admin"
        ],
        "summary": "Modify Center",
        "description": "API endpoint to modify center by SuperAdmin or an Admin",
        "operationId": "ModifyCenter",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            },
            "example": "application/x-www-form-urlencoded"
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "required": [
                  "name",
                  "location",
                  "description",
                  "capacity",
                  "facilities",
                  "image",
                  "price"
                ],
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "The Gooche"
                  },
                  "location": {
                    "type": "string",
                    "example": "6, Aminu street Garki Abuja"
                  },
                  "description": {
                    "type": "string",
                    "example": "For your eyes only"
                  },
                  "capacity": {
                    "type": "string",
                    "example": "1000"
                  },
                  "facilities": {
                    "type": "string",
                    "example": "swimming pool"
                  },
                  "image": {
                    "type": "string",
                    "example": "\"\""
                  },
                  "price": {
                    "type": "string",
                    "example": "20000"
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Admin"
        ],
        "summary": "Delete Center",
        "description": "API endpoint to delete centers",
        "operationId": "DeleteCenter",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/api/v1/events": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get User Events",
        "description": "API endpoint to get events created by user/admin",
        "operationId": "GetUserEvents",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            },
            "example": "application/x-www-form-urlencoded"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "post": {
        "tags": [
          "Users"
        ],
        "summary": "Create event",
        "description": "API endpoint to create an event",
        "operationId": "CreateEvent",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            },
            "example": "application/x-www-form-urlencoded"
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "required": [
                  "name",
                  "centerId",
                  "date",
                  "time"
                ],
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Beach Party"
                  },
                  "centerId": {
                    "type": "string",
                    "example": "2"
                  },
                  "date": {
                    "type": "string",
                    "example": "2018-12-31"
                  },
                  "time": {
                    "type": "string",
                    "example": "4 pm"
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/api/v1/events/{eventId}": {
      "get": {
        "tags": [
          "Users"
        ],
        "summary": "Get One Event",
        "description": "API endpoint to get one event",
        "operationId": "GetOneEvent",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "put": {
        "tags": [
          "Users"
        ],
        "summary": "Modify Event",
        "description": "API endpoint for users to modify their events",
        "operationId": "ModifyEvent",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            },
            "example": "application/x-www-form-urlencoded"
          }
        ],
        "requestBody": {
          "content": {
            "application/x-www-form-urlencoded": {
              "schema": {
                "required": [
                  "name",
                  "centerId",
                  "date",
                  "time"
                ],
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "example": "Launcheon"
                  },
                  "centerId": {
                    "type": "string",
                    "example": "2"
                  },
                  "date": {
                    "type": "string",
                    "example": "2019-01-01"
                  },
                  "time": {
                    "type": "string",
                    "example": "12 pm"
                  }
                }
              }
            }
          },
          "required": false
        },
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      },
      "delete": {
        "tags": [
          "Users"
        ],
        "summary": "Delete Event",
        "description": "API endpoint to delete events",
        "operationId": "DeleteEvent",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
          },
          {
            "name": "Content-Type",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "application/x-www-form-urlencoded"
            },
            "example": "application/x-www-form-urlencoded"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    },
    "/api/v1/users/{userId}": {
      "put": {
        "tags": [
          "SuperAdmin"
        ],
        "summary": "Upgrade Users to Admin",
        "description": "API endpoint to upgrade users to Admin",
        "operationId": "UpgradeUsersToAdmin",
        "parameters": [
          {
            "name": "x-access-token",
            "in": "header",
            "description": "",
            "required": true,
            "style": "simple",
            "explode": false,
            "schema": {
              "type": "string",
              "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
            },
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjEsImlzYWRtaW4iOnRydWUsInVzZXJyb2xlIjoic3VwZXJhZG1pbiIsImlhdCI6MTUyNjQwNzcxNywiZXhwIjoxNTI2NTgwNTE3fQ.D2OiADSZWRBk4lZDp0Ys3nr5i354x8wfMqugKkXTJt8"
          }
        ],
        "responses": {
          "200": {
            "description": ""
          }
        },
        "deprecated": false,
        "security": [],
        "x-operation-settings": {
          "CollectParameters": false,
          "AllowDynamicQueryParameters": false,
          "AllowDynamicFormParameters": false,
          "IsMultiContentStreaming": false
        }
      }
    }
  },
  "components": {
    "schemas": {
      "SignUp": {
        "title": "Sign Up",
        "required": [
          "status",
          "message",
          "data"
        ],
        "type": "object",
        "properties": {
          "status": {
            "type": "string",
            "example": "Success"
          },
          "message": {
            "type": "string",
            "example": "User successfully signed up"
          },
          "data": {
            "example": {
              "firstname": "kunle",
              "lastname": "williams",
              "role": "user",
              "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjQsImlzYWRtaW4iOmZhbHNlLCJ1c2Vycm9sZSI6InVzZXIiLCJpYXQiOjE1MjY0MDgzMzMsImV4cCI6MTUyNjU4MTEzM30.ziozx4c9yxvPDeGBefawbHEzeB0dh6Kz1-2EkNyvb-4"
            },
            "$ref": "#/components/schemas/Data"
          }
        },
        "example": {
          "status": "Success",
          "message": "User successfully signed up",
          "data": {
            "firstname": "kunle",
            "lastname": "williams",
            "role": "user",
            "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjQsImlzYWRtaW4iOmZhbHNlLCJ1c2Vycm9sZSI6InVzZXIiLCJpYXQiOjE1MjY0MDgzMzMsImV4cCI6MTUyNjU4MTEzM30.ziozx4c9yxvPDeGBefawbHEzeB0dh6Kz1-2EkNyvb-4"
          }
        }
      },
      "Data": {
        "title": "Data",
        "required": [
          "firstname",
          "lastname",
          "role",
          "token"
        ],
        "type": "object",
        "properties": {
          "firstname": {
            "type": "string",
            "example": "kunle"
          },
          "lastname": {
            "type": "string",
            "example": "williams"
          },
          "role": {
            "type": "string",
            "example": "user"
          },
          "token": {
            "type": "string",
            "example": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjQsImlzYWRtaW4iOmZhbHNlLCJ1c2Vycm9sZSI6InVzZXIiLCJpYXQiOjE1MjY0MDgzMzMsImV4cCI6MTUyNjU4MTEzM30.ziozx4c9yxvPDeGBefawbHEzeB0dh6Kz1-2EkNyvb-4"
          }
        },
        "example": {
          "firstname": "kunle",
          "lastname": "williams",
          "role": "user",
          "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyaWQiOjQsImlzYWRtaW4iOmZhbHNlLCJ1c2Vycm9sZSI6InVzZXIiLCJpYXQiOjE1MjY0MDgzMzMsImV4cCI6MTUyNjU4MTEzM30.ziozx4c9yxvPDeGBefawbHEzeB0dh6Kz1-2EkNyvb-4"
        }
      }
    }
  }
}